services:
  - type: web
    name: proyecto-uni
    env: python
    runtime: python-3.11
    plan: free
    buildCommand: python -m pip install --upgrade pip setuptools wheel && python -m pip install -r requirements.txt
    startCommand: python -m pip install --upgrade pip setuptools wheel && PYTHONPATH=$(pwd)/pantalla/pantalla waitress-serve --port=$PORT django_app.wsgi:application
