"""
Django settings for django_app project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# After consolidating repository under the `django_app` folder,
# make BASE_DIR point to the project root (this file's parent).
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@%i@jah3u_9f!b*vpzdx(15!xw9c@9187mt%n&4o994j!to=!s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow host from Railway (RAILWAY_PUBLIC_DOMAIN), Render (RENDER_EXTERNAL_HOSTNAME), or env.
# In development, also allow localhost + 127.0.0.1.
railway_host = os.environ.get("RAILWAY_PUBLIC_DOMAIN")
render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
base_hosts = ["127.0.0.1", "localhost"]
if railway_host:
    base_hosts.append(railway_host)
if render_host:
    base_hosts.append(render_host)

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", ",".join(base_hosts)).split(",")

# CSRF trusted origins: Railway, Render, or env.
csrf_trusted = []
if railway_host:
    csrf_trusted.append(f"https://{railway_host}")
if render_host:
    csrf_trusted.append(f"https://{render_host}")

csrf_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if csrf_env:
    csrf_trusted += [h.strip() for h in csrf_env.split(",") if h.strip()]

CSRF_TRUSTED_ORIGINS = csrf_trusted


# Application definition

INSTALLED_APPS = [
    # The `homepage` app lives inside the django_app package.
    'django_app.homepage.apps.HomepageConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_app.core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files directly.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The project is packaged under `django_app`, so URLconf must match.
ROOT_URLCONF = 'django_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_app.core.context_processors.contador_carrito',  # procesador de contexto personalizado
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL if DATABASE_URL is set (e.g., on Render), otherwise use SQLite for local dev.
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# In production (Render, etc) we collect all static files into this folder
# and serve them with WhiteNoise.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [
    str(BASE_DIR / "static"),
    # Also include legacy asset folders used by templates (Presento theme, SFI assets)
    # expose the legacy asset folders (moved into extras/) so requests for 'assets/...' still resolve
    # Presento/assets/... and SFI-V2-master/assets/...
    # legacy themes moved to `extras/` under this project folder
    str(BASE_DIR / 'extras' / 'Presento'),
    str(BASE_DIR / 'extras' / 'SFI-V2-master'),
    # keep app-level static path
    str(BASE_DIR / 'static'),
]

# Use WhiteNoise to serve static files in production (especially when running under Waitress).
# See https://whitenoise.evans.io/en/stable/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
