# Generated by Django 5.2.8 on 2026-04-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salida_pago_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritodecompras',
            options={},
        ),

        
        migrations.AddField(
            model_name='carritodecompras',
            name='Nota_Entrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.nota_entrega'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
    ]
