# Generated by Django 5.2.8 on 2026-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carritodecompras_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_entrega',
            name='bcv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
