# Generated by Django 5.1.3 on 2026-01-03 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_cliente_alter_product_img_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_actual', models.FloatField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tasa BCV',
                'verbose_name_plural': 'Tasas BCV',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre')),
                ('descripcion_categoria', models.CharField(blank=True, max_length=45, null=True, verbose_name='Descripción')),
                ('rif_proveedor', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('cedula_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('status_pago', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(blank=True, max_length=45, null=True)),
                ('precio_unidad', models.FloatField(blank=True, null=True)),
                ('sub_total_servicio', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioSublimado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total_sublimado', models.FloatField(blank=True, null=True)),
                ('precio_unidad', models.FloatField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_de_pedido', models.DateField(blank=True, null=True)),
                ('fecha_de_entrega', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_suministro', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_stock', models.FloatField(blank=True, null=True)),
                ('stock_minimo', models.FloatField(blank=True, null=True)),
                ('precio_costo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Clientes',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cedula_dni',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cedula_dni_representante',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rif_empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rif_empresarial',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='CarritoDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_carrito', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito de Compras',
                'verbose_name_plural': 'Carritos de Compras',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('marca_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('max_producto', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('status_producto', models.BooleanField(default=True)),
                ('cantidad_disponible', models.IntegerField(blank=True, null=True)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_item', models.IntegerField(blank=True, null=True)),
                ('sub_total_item', models.FloatField(blank=True, null=True)),
                ('estado_disponibilidad', models.BooleanField(default=True)),
                ('carrito_de_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carritodecompras')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('bcv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bcv')),
                ('carrito_de_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carritodecompras')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metodopago')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida (Venta)',
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total_servicio', models.FloatField(blank=True, null=True)),
                ('carrito_de_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carritodecompras')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicio')),
                ('servicio_sublimado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviciosublimado')),
            ],
        ),
        migrations.CreateModel(
            name='SublimadoConsumoSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.FloatField(blank=True, null=True)),
                ('servicio_sublimado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serviciosublimado')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada_por_unidad', models.FloatField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suministro')),
            ],
            options={
                'verbose_name': 'Insumo por Servicio',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipocliente'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
