# Generated by Django 5.2.8 on 2026-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carritodecompras_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_entrega',
            name='bcv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
