# Generated by Django 5.1.3 on 2026-01-18 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bcv_categoria_empleado_metodopago_rol_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cambiada', models.FloatField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo_cambio', models.CharField(blank=True, max_length=255, null=True)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suministro')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Inventario',
                'verbose_name_plural': 'Historiales de Inventario',
            },
        ),
    ]
