# Generated by Django 5.1.3 on 2026-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nota_entrega_bcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_entrega',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
