# Generated by Django 5.2.8 on 2026-04-25 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nota_entrega_comprobante_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Marca de Producto',
                'verbose_name_plural': 'Marcas de Productos',
            },
        ),
        migrations.AddField(
            model_name='carritodecompras',
            name='talla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nota_entrega',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nota_entrega',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('PAGO MOVIL', 'Pago Móvil'), ('TARJETA', 'Tarjeta')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca_producto'),
        ),
        migrations.CreateModel(
            name='SolicitudSublimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('imagen_sublimacion', models.ImageField(blank=True, null=True, upload_to='sublimaciones/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VINCULADA', 'Vinculada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('carrito_de_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_sublimacion', to='core.carritodecompras')),
                ('nota_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_sublimacion', to='core.nota_entrega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_sublimacion', to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_sublimacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
