# Generated by Django 5.1.3 on 2026-04-18 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nota_entrega_comprobante_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='nota_entrega',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nota_entrega',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('PAGO MOVIL', 'Pago Móvil'), ('TARJETA', 'Tarjeta')], max_length=20, null=True),
        ),
    
    ]
