# Generated by Copilot on 2026-04-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nota_entrega_comprobante_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSublimacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('imagen_sublimacion', models.ImageField(blank=True, null=True, upload_to='sublimaciones/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VINCULADA', 'Vinculada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('carrito_de_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_sublimacion', to='core.carritodecompras')),
                ('nota_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_sublimacion', to='core.nota_entrega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_sublimacion', to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_sublimacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
