# Generated by Django 5.1.3 on 2026-04-18 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nota_entrega_comprobante_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Marca de Producto',
                'verbose_name_plural': 'Marcas de Productos',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca_producto'),
        ),
    ]
