# Generated by Django 5.1.3 on 2026-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_marca_producto_carritodecompras_talla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca_producto',
            name='nombre_marca',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
