# Generated by Copilot on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitud_sublimacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritodecompras',
            name='talla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
