# Generated by Django 5.1.3 on 2026-01-18 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_motivo_cambio_historial_inventario_motivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_inventario',
            old_name='suministro',
            new_name='cantidad_anterior',
        ),
        migrations.RemoveField(
            model_name='historial_inventario',
            name='cantidad_cambiada',
        ),
        migrations.AddField(
            model_name='historial_inventario',
            name='cantidad_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_por_suministro_nueva', to='core.producto'),
        ),
    ]
