# Generated by Django 5.1.3 on 2026-01-18 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_suministro_historial_inventario_cantidad_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_inventario',
            name='Motivo',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
