# Generated by Copilot on 2026-05-02

from django.db import migrations, models
import django.db.models.deletion


def seed_size_stock(apps, schema_editor):
    Producto = apps.get_model('core', 'Producto')
    ProductoTallaStock = apps.get_model('core', 'ProductoTallaStock')

    for producto in Producto.objects.select_related('categoria').all():
        categoria_nombre = (getattr(getattr(producto, 'categoria', None), 'nombre_categoria', '') or '').strip()
        if categoria_nombre == 'Camisas':
            tallas = ['S', 'M', 'L', 'XL', 'XXL']
            default_talla = 'M'
        elif categoria_nombre == 'Tazas':
            tallas = ['Unica']
            default_talla = 'Unica'
        else:
            continue

        stock_total = int(producto.cantidad_disponible or 0)
        for talla in tallas:
            ProductoTallaStock.objects.get_or_create(
                producto_id=producto.id,
                talla=talla,
                defaults={'stock_disponible': stock_total if talla == default_talla else 0},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTallaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_por_talla', to='core.producto')),
            ],
            options={
                'verbose_name': 'Stock por talla',
                'verbose_name_plural': 'Stocks por talla',
                'ordering': ['producto__nombre_producto', 'talla'],
                'unique_together': {('producto', 'talla')},
            },
        ),
        migrations.AddField(
            model_name='solicitudsublimacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(seed_size_stock, migrations.RunPython.noop),
    ]