# Generated by Django 5.1.3 on 2026-01-18 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_fecha_movimiento_historial_inventario_fecha_ajuste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_inventario',
            old_name='Motivo',
            new_name='motivo',
        ),
        migrations.RemoveField(
            model_name='historial_inventario',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='historial_inventario',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='historial_inventario',
            name='cantidad_anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historial_inventario',
            name='cantidad_nueva',
            field=models.IntegerField(default=0),
        ),
    ]
