# Generated by Django 5.1.3 on 2026-05-03 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productotallastock_solicitudsublimacion_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='nota_entrega',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    
    ]
