# Generated by Copilot on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_securityquestion_usersecurityanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]