# Generated by Django 5.2.8 on 2026-05-31 04:25

from django.db import migrations, models


def pasar_documento_a_id(apps, schema_editor):
    Cliente = apps.get_model('core', 'Cliente') # Asumiendo que 'core' es el label de tu app
    
    for cliente in Cliente.objects.all():
        if cliente.documento: 
            Cliente.objects.filter(pk=cliente.pk).update(id=cliente.documento)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_nota_entrega_descuento_total_bruto'),
    ]

    operations = [
        # 1. Rompemos la relación actual usando EL NOMBRE EXACTO de tu Railway
        #migrations.RunSQL(
            #sql="ALTER TABLE core_nota_entrega DROP FOREIGN KEY core_nota_entrega_cliente_id_b5d1b37f_fk_core_cliente_id;"
        #),

        # 2. Preparamos la columna hija para recibir texto
        migrations.RunSQL(
            sql="ALTER TABLE core_nota_entrega MODIFY cliente_id VARCHAR(45);"
        ),

        # 3. La operación de Django para cambiar la tabla cliente
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),

        # 4. Reconectamos las tablas con CASCADE apuntando a core_cliente
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_nota_entrega ADD CONSTRAINT core_nota_entrega_cliente_fk_cascade 
            FOREIGN KEY (cliente_id) REFERENCES core_cliente(id) 
            ON UPDATE CASCADE;
            """
        ),

        # 5. Pasamos los datos
        migrations.RunPython(pasar_documento_a_id),
    ]