# Generated by Django 5.2.8 on 2026-05-31 04:25

from django.db import migrations, models


def pasar_documento_a_id(apps, schema_editor):
    Cliente = apps.get_model('core', 'Cliente') # Asumiendo que 'core' es el label de tu app
    
    for cliente in Cliente.objects.all():
        if cliente.documento: 
            Cliente.objects.filter(pk=cliente.pk).update(id=cliente.documento)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_nota_entrega_descuento_total_bruto'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Apagamos la seguridad
            SET FOREIGN_KEY_CHECKS = 0;

            -- (Ya no necesitamos borrar la llave porque ya se borró)

            -- 2. Convertimos la columna hija a VARCHAR
            ALTER TABLE core_nota_entrega 
            MODIFY cliente_id VARCHAR(45);

            -- 3. Convertimos la columna padre a VARCHAR
            ALTER TABLE core_cliente 
            MODIFY id VARCHAR(45);

            -- 4. Actualizamos los datos de los hijos
            UPDATE core_nota_entrega ne
            INNER JOIN core_cliente c ON ne.cliente_id = c.id
            SET ne.cliente_id = c.documento
            WHERE c.documento IS NOT NULL AND c.documento != '';

            -- 5. Actualizamos los datos de los padres
            UPDATE core_cliente 
            SET id = documento 
            WHERE documento IS NOT NULL AND documento != '';

            -- 6. Volvemos a conectar las tablas (Ya con el formato VARCHAR correcto)
            ALTER TABLE core_nota_entrega 
            ADD CONSTRAINT core_nota_entrega_cliente_fk_cascade 
            FOREIGN KEY (cliente_id) REFERENCES core_cliente(id) 
            ON UPDATE CASCADE;

            -- 7. Encendemos la seguridad de nuevo
            SET FOREIGN_KEY_CHECKS = 1;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Le avisamos a Django que el cambio ya está hecho
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='cliente',
                    name='id',
                    field=models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
            ]
        )
    ]