# Generated by Django 5.2.8 on 2026-05-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='documento',
        ),
    ]
