# Generated by Django 5.2.8 on 2026-05-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cliente_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rif_empresarial',
        ),
    ]
