# Generated by Django 5.2.8 on 2026-05-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fix_missing_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='rif_proveedor',
        ),
    ]
