# Generated by Django 5.2.8 on 2026-05-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_categoria_rif_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='direccion_proveedor',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='telefono_proveedor',
        ),
    ]
