# Generated by Django 5.2.8 on 2026-06-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_categoria_direccion_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id',
            new_name='cedula',
        ),
    ]
