# Generated by Django 5.2.8 on 2026-06-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_id_cliente_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
    ]
