# Generated by Django 5.2.8 on 2026-06-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota_entrega',
            name='cliente_direccion',
        ),
        migrations.RemoveField(
            model_name='nota_entrega',
            name='cliente_documento',
        ),
        migrations.RemoveField(
            model_name='nota_entrega',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='nota_entrega',
            name='metodo_pago',
        ),
    ]
