# Generated by Django 5.2.8 on 2026-06-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_nota_entrega_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_documento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='nota_entrega',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cliente_cedula', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
    ]
