# Generated by Django 5.2.8 on 2026-06-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_nota_entrega_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_entrega',
            name='cliente_documento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='nota_entrega',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='nota_entrega',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        
       
    ]
