# Generated by Django 5.2.8 on 2026-06-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cliente_cliente_direccion_cliente_cliente_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_nombre',
        ),
    ]
