# Generated by Django 5.1.3 on 2025-11-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='Precio')),
                ('img', models.URLField(blank=True, verbose_name='Imagen URL')),
                ('desc', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
