# Generated by Django 5.1.3 on 2025-12-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_cliente', models.CharField(choices=[('1', 'Persona Natural'), ('2', 'Persona Jurídica')], max_length=1, verbose_name='Tipo de cliente')),
                ('nombre_cliente', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido_cliente', models.CharField(blank=True, max_length=45, verbose_name='Apellido')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('telefono_cliente', models.CharField(blank=True, max_length=11, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cedula_dni', models.CharField(blank=True, max_length=11, verbose_name='Cédula / DNI')),
                ('rif_empresa', models.CharField(blank=True, max_length=22, verbose_name='RIF')),
                ('nombre_empresa', models.CharField(blank=True, max_length=255, verbose_name='Nombre empresa')),
                ('cedula_dni_representante', models.CharField(blank=True, max_length=11, verbose_name='Cédula representante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nombre de producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category'),
        ),
    ]
