# Generated by Django 5.1.3 on 2026-01-18 22:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historial_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_inventario',
            old_name='motivo_cambio',
            new_name='Motivo',
        ),
        migrations.RenameField(
            model_name='historial_inventario',
            old_name='fecha_cambio',
            new_name='fecha_movimiento',
        ),
        migrations.AddField(
            model_name='historial_inventario',
            name='nombre_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto'),
        ),
        migrations.AddField(
            model_name='historial_inventario',
            name='tipo_movimiento',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial_inventario',
            name='cantidad_cambiada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historial_inventario',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_por_suministro', to='core.producto'),
        ),
    ]
