# Generated by Django 5.1.3 on 2026-01-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_historial_inventario_motivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_inventario',
            old_name='fecha_movimiento',
            new_name='fecha_ajuste',
        ),
    ]
