# Generated by Django 5.1.3 on 2026-01-18 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_motivo_historial_inventario_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_inventario',
            name='usuario_responsable',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
